project_id = "rejerjibsoadxwfqofda"

[functions.generate-payouts]
verify_jwt = false

[functions.sync-ics]
verify_jwt = false

[functions.dispatch-notifications]
verify_jwt = false

[functions.fetch-events]
verify_jwt = false

[functions.compute-price-suggestions]
verify_jwt = false